"""added category model

Revision ID: 83d75c811e72
Revises: 
Create Date: 2026-04-28 19:50:09.848429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d75c811e72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_habits_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_habits_category_id', 'categories', ['category_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_habits_category_id'))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
